spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lwz7254591

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

  redis:
    database: 0
    password: root
    host: localhost
    port: 6379


logging:
  config: D:\Application\project\JAVA_PROJECT\separate\background\jpa_blog\src\main\resources\logback-spring.xml

server:
  port: 8090


swagger:
  enable: true

notice: "这里是公告哦"

